name: Binary Translated Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{github.workspace}}/tests/unit

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-12-riscv64-linux-gnu g++-12-riscv64-linux-gnu
        git submodule update --init ${{github.workspace}}/tests/Catch2
        git submodule update --init ${{github.workspace}}/tests/unit/ext/lodepng

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DRISCV_THREADED=ON -DRISCV_BINARY_TRANSLATION=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build the unittests
      run: cmake --build ${{github.workspace}}/build --parallel 4

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: CFLAGS=-O0 ctest --verbose . -j4
